---

version: '2'
services:
  centos_7:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_CentOS_7
      args:
        ANSIBLE_VERSION: 2.6.0
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
  debian_8_10:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Debian_8.10
      args:
        ANSIBLE_VERSION: 2.6.0
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
  debian_9_4:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Debian_9.4
      args:
        ANSIBLE_VERSION: 2.6.0
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
  ubuntu_16_04:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Ubuntu_16.04
      args:
        ANSIBLE_VERSION: 2.6.0
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
  ubuntu_17_10:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Ubuntu_17.10
      args:
        ANSIBLE_VERSION: 2.6.0
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
  ubuntu_18_04:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Ubuntu_18.04
      args:
        ANSIBLE_VERSION: 2.6.0
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
  ubuntu_18_10:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Ubuntu_18.10
      args:
        ANSIBLE_VERSION: 2.6.0
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
